"""
Base Models for Weave Backend
Story 1.5.2: Backend API/Model Standardization

ARCHITECTURE NOTE:
This project uses Supabase (PostgreSQL) for database, NOT SQLAlchemy ORM.
- Database tables: Created via Supabase SQL migrations (supabase/migrations/)
- Python models: Pydantic models for API request/response validation
- Data access: Supabase Python client (from supabase import create_client)

This file provides base Pydantic models for consistent API schemas.
For database table patterns, see: scripts/templates/database_table_template.sql
"""

from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

# ============================================================================
# BASE RESPONSE MODEL
# ============================================================================

class BaseResponseModel(BaseModel):
    """
    Base model for all API response schemas

    Includes standard fields that exist on all database tables:
    - id (UUID primary key)
    - created_at (timestamp)
    - updated_at (timestamp)
    - deleted_at (timestamp, nullable - for soft delete)
    """

    id: UUID = Field(..., description="Resource UUID")
    created_at: datetime = Field(..., description="Creation timestamp (UTC)")
    updated_at: datetime = Field(..., description="Last update timestamp (UTC)")
    deleted_at: Optional[datetime] = Field(None, description="Soft delete timestamp (UTC)")

    model_config = ConfigDict(
        from_attributes=True,  # Allow ORM mode (if needed)
        json_schema_extra={
            "examples": [
                {
                    "id": "550e8400-e29b-41d4-a716-446655440000",
                    "created_at": "2025-12-23T10:00:00Z",
                    "updated_at": "2025-12-23T10:00:00Z",
                    "deleted_at": None
                }
            ]
        }
    )

    @property
    def is_deleted(self) -> bool:
        """Check if resource is soft deleted"""
        return self.deleted_at is not None


# ============================================================================
# BASE CREATE MODEL
# ============================================================================

class BaseCreateModel(BaseModel):
    """
    Base model for all API create request schemas

    Does NOT include:
    - id (auto-generated by database)
    - created_at, updated_at (auto-generated by database)
    - deleted_at (only set during soft delete)

    Subclass this for resource-specific create models.
    """

    model_config = ConfigDict(
        # Strict validation
        str_strip_whitespace=True,
        # Allow extra fields to be ignored (permissive)
        extra="ignore"
    )


# ============================================================================
# BASE UPDATE MODEL
# ============================================================================

class BaseUpdateModel(BaseModel):
    """
    Base model for all API update request schemas

    All fields should be Optional to support partial updates.
    Only fields with non-None values will be updated.

    Does NOT include:
    - id (cannot be changed)
    - created_at (cannot be changed)
    - updated_at (auto-updated by database)
    - deleted_at (only set during soft delete operation)

    Subclass this for resource-specific update models.
    """

    model_config = ConfigDict(
        # Strict validation
        str_strip_whitespace=True,
        # Allow extra fields to be ignored (permissive)
        extra="ignore"
    )


# ============================================================================
# USAGE EXAMPLES
# ============================================================================

"""
Example: Goal Resource Models

from app.models.base import BaseCreateModel, BaseUpdateModel, BaseResponseModel

# Create Schema (POST /api/goals)
class GoalCreate(BaseCreateModel):
    title: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = Field(None, max_length=1000)
    emoji: str = Field(..., max_length=10)

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [{
                "title": "Learn Spanish",
                "description": "Become conversational in 10 days",
                "emoji": "🇪🇸"
            }]
        }
    )

# Update Schema (PUT /api/goals/{id})
class GoalUpdate(BaseUpdateModel):
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = Field(None, max_length=1000)
    emoji: Optional[str] = Field(None, max_length=10)
    is_archived: Optional[bool] = None

# Response Schema (returned by all goal endpoints)
class GoalResponse(BaseResponseModel):
    user_id: UUID
    title: str
    description: Optional[str]
    emoji: str
    is_archived: bool
    status: str  # active, completed, abandoned

    # Additional computed fields
    progress_percentage: float = Field(0.0, ge=0, le=100)

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "examples": [{
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "user_id": "660e8400-e29b-41d4-a716-446655440000",
                "title": "Learn Spanish",
                "description": "Become conversational in 10 days",
                "emoji": "🇪🇸",
                "is_archived": False,
                "status": "active",
                "progress_percentage": 45.5,
                "created_at": "2025-12-23T10:00:00Z",
                "updated_at": "2025-12-23T10:00:00Z",
                "deleted_at": None
            }]
        }
    )
"""


# ============================================================================
# SOFT DELETE PATTERN (DATABASE SIDE)
# ============================================================================

"""
Database Table Pattern with Soft Delete:

CREATE TABLE goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id),
    title TEXT NOT NULL,
    description TEXT,
    emoji TEXT NOT NULL,
    is_archived BOOLEAN DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'active',

    -- Standard timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,  -- Soft delete

    CONSTRAINT goals_status_check CHECK (status IN ('active', 'completed', 'abandoned'))
);

-- Index for soft delete filtering
CREATE INDEX idx_goals_deleted_at ON goals(deleted_at) WHERE deleted_at IS NULL;

-- Index for user queries (only active records)
CREATE INDEX idx_goals_user_active ON goals(user_id, deleted_at) WHERE deleted_at IS NULL;

-- Trigger to auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_goals_updated_at BEFORE UPDATE ON goals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- RLS Policies (Story 0.4)
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_manage_own_goals" ON goals
    FOR ALL
    USING (user_id IN (
        SELECT id FROM user_profiles WHERE auth_user_id = auth.uid()::text
    ));

-- Application Code Pattern:

# Soft delete (set deleted_at timestamp)
supabase.table('goals').update({
    'deleted_at': datetime.utcnow().isoformat()
}).eq('id', goal_id).execute()

# Query active records only (exclude soft deleted)
supabase.table('goals').select('*').is_('deleted_at', 'null').execute()

# Restore soft deleted record
supabase.table('goals').update({
    'deleted_at': None
}).eq('id', goal_id).execute()

# Hard delete (permanent removal - use with caution!)
supabase.table('goals').delete().eq('id', goal_id).execute()
"""


# ============================================================================
# NAMING CONVENTIONS
# ============================================================================

"""
Database Naming (PostgreSQL/Supabase):
- Tables: snake_case, plural (e.g., user_profiles, journal_entries)
- Columns: snake_case (e.g., user_id, local_date, scheduled_for_date)
- Foreign keys: {table}_id (e.g., user_id, goal_id)
- Indexes: idx_{table}_{columns} (e.g., idx_completions_user_date)
- Constraints: {table}_{column}_check (e.g., goals_status_check)

Python Models (Pydantic):
- Classes: PascalCase (e.g., GoalCreate, UserProfileResponse)
- Fields: snake_case to match database columns
- Files: snake_case (e.g., goal.py, user_profile.py)

API Endpoints (FastAPI):
- Routes: kebab-case for multi-word resources (e.g., /api/journal-entries)
- Query params: snake_case (e.g., ?user_id=xxx&local_date=2025-12-23)
"""
